### ISSUE TITLE
Understanding output - what are Faces?

### ISSUE THREAD

**Issue by 0xPaladin** [arscan/hexasphere.js#1]
Each tile has a:
- boundary
- centerPoint
- faces

Each centerPoint has an array of Faces.

Are the Faces the same? What do they represent?

**Comment by arscan** [comment]
I believe each face is a triangle and is an intermediate biproduct of the algorithm used to generate this.  I probably should delete them once this is done being generated. boundary + centerpoint for the tile should be enough to render.

Note: it has been a few years since I've looked at this, so I could be forgetting something.

**Comment by 0xPaladin** [comment]
Thanks. I saw it had been a while.
I was playing around with it and I was trying to determine how to get the neighbors of a particular hex.

**Comment by arscan** [comment]
Ahhh, hmmm, I'm not sure if you can figure that out with the information that I have saved.  It should be possible to figure that out quickly during one of the steps of hte algorithm, though I couldn't say where exactly without spending some time digging into it.

**Comment by 0xPaladin** [comment]
ok, thanks.
