### ISSUE TITLE
How would i go about making "thick" tiles?

### ISSUE THREAD

**Issue by AKRFranko** [arscan/hexasphere.js#2]
I'm trying to build something using THREE.js and Hexasphere. I've based my code of your example found here: https://www.robscanlon.com/hexasphere/  

But I 'can't wrap my head around how I'd modify the vertice/face loops to make the tiles into hexagonal/pentagonal prisms. Can you give me a hint?

**Comment by arscan** [comment]
I did a quick example of one way you could do it on this branch: https://github.com/arscan/hexasphere.js/tree/tiles-with-depth

![tiles_with_depth](https://cloud.githubusercontent.com/assets/412901/24573499/c2296630-1651-11e7-92e1-fa24017d91a4.png)

Doesn't look that great because I am not using lights and shading... changing the material and adding some lights would probably make it look much better.  But I just wanted to mock something up for you.

Is this what you are looking to do?  Hope it helps!

**Comment by AKRFranko** [comment]
Oh wow! Thanks! I've only skimmed through the example so far, but I'm pretty certain I can pick up from here. If I end up with something amazing I'll be sure to share and credit!

**Comment by arscan** [comment]
Glad to help, thanks for using my little library! :)

**Comment by AKRFranko** [comment]
Man, I'm trying to create something and have fun and keept getting lost in icosahedron and non-regular dodecahedon and matrixUpdates and whatnot... which wasn't getting me anywhere near my goal then lo an behold: Your little library! Which cuts straight to chase and gives me exactly what I was trying to do minus one small detail and BAM! You just hand it to me. Awesome! I wish work stuff was as awesome!
